name: Deployment Stage - Deploy S3

on:
  workflow_call:
    secrets:
      scw_access_key:
        required: true
      scw_secret_key:
        required: true
      scw_project_id:
        required: true

jobs:
  plan:
    name: plan
    runs-on: ubuntu-22.04

    env:
      TF_VAR_scw_access_key: ${{ secrets.scw_access_key }}
      TF_VAR_scw_secret_key: ${{ secrets.scw_secret_key }}
      TF_VAR_scw_project_id: ${{ secrets.scw_project_id }}
      AWS_ACCESS_KEY_ID: ${{ secrets.scw_access_key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.scw_secret_key }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3 

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Apply
        run: |
          cd 01-setup-s3-for-remote-state/
          terraform init
          terraform plan -input=false -detailed-exitcode
