name: Commit Stage - Validate Terraform

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
    secrets:
      scw_access_key:
        required: true
      scw_secret_key:
        required: true
      scw_project_id:
        required: true

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: ${{ inputs.path }}

    env:
      TF_VAR_scw_access_key: ${{ secrets.scw_access_key }}
      TF_VAR_scw_secret_key: ${{ secrets.scw_secret_key }}
      TF_VAR_scw_project_id: ${{ secrets.scw_project_id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3 

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.scw_access_key }} --profile lawandorga
          aws configure set aws_secret_access_key ${{ secrets.scw_secret_key }} --profile lawandorga

      - name: Terraform Validate
        id: plan
        shell: bash
        run: |
          terraform init
          terraform plan -detailed-exitcode
          echo "::set-output name=exitcode::$?"
      
      - name: Check Plan Result
        if: steps.plan.outputs.exitcode == '2' || steps.plan.outputs.exitcode == '1'
        run: |
          echo "Changes Detected Or Terraform Plan Failed"
          echo "Check The Previous Terraform Validate Step"
          exit 1
        shell: bash
